name: Deploy to Firebase Hosting on PR
on: pull_request

# Dependabot gets read-only access by default
permissions:
  checks: write
  pull-requests: write

jobs:
  build_and_preview:
    if: ${{ github.event.pull_request.head.repo.full_name == github.repository }}
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4

      - uses: actions/setup-node@v4
        with:
          node-version: 22
          cache: yarn

      - uses: actions/cache@v4
        with:
          path: |
            **/node_modules
          key: ${{ hashFiles('**/yarn.lock') }}

      - run: yarn install --frozen-lockfile
      - run: yarn build
      - run: make convert-netlify-redirect-to-firebase

      - uses: FirebaseExtended/action-hosting-deploy@v0
        with:
          repoToken: '${{ secrets.GITHUB_TOKEN }}'
          firebaseServiceAccount: '${{ secrets.FIREBASE_SERVICE_ACCOUNT_WKTKJP }}'
          projectId: wktkjp

      - run: make clean
