name: Deploy to Firebase
on:
  push:
    branches:
      - master

jobs:
  firebase-deploy:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@master
      
      - uses: actions/setup-node@v3
        with:
          node-version: 18

      - uses: actions/cache@v2
        with:
          path: |
            **/node_modules
          key: ${{ hashFiles('**/yarn.lock') }}

      - run: make deploy
        env:
          FIREBASE_TOKEN: ${{ secrets.FIREBASE_TOKEN }}

      - name: Generate tag
        id: generate-tag
        run: echo "::set-output name=value::$(date '+%Y%m%d-%H%M%S')"
        env:
          TZ: Asia/Tokyo

      - name: Create Release
        uses: actions/create-release@v1
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          tag_name: ${{ steps.generate-tag.outputs.value }}
          release_name: Deployment @ ${{ steps.generate-tag.outputs.value }}
          body: Deployment @ ${{ steps.generate-tag.outputs.value }}
